<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Probook15-650Series" failures="3" tests="4" name="chrome Test" time="29.841" errors="0" timestamp="2023-04-15T12:45:14 GST">
  <testcase classname="com.obsqura.testScripts.LoginTest" name="verify_login_with_Credentials" time="1.869"/>
  <testcase classname="com.obsqura.testScripts.LoginTest" name="verify_login_with_Credentials" time="1.009">
    <failure type="java.lang.AssertionError" message="Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at com.obsqura.testScripts.LoginTest.verify_login_with_Credentials(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_login_with_Credentials -->
  <testcase classname="com.obsqura.testScripts.LoginTest" name="verify_login_with_Credentials" time="0.664">
    <failure type="java.lang.AssertionError" message="Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at com.obsqura.testScripts.LoginTest.verify_login_with_Credentials(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_login_with_Credentials -->
  <testcase classname="com.obsqura.testScripts.LoginTest" name="verify_login_with_Credentials" time="0.791">
    <failure type="java.lang.AssertionError" message="Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login failed expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at com.obsqura.testScripts.LoginTest.verify_login_with_Credentials(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_login_with_Credentials -->
</testsuite> <!-- chrome Test -->
